### PR TITLE
Bug fixes and minor tweaks.

### PR DESCRIPTION
**Pull request by tombastianello**
Was about to write something like this for myself, but I'm glad someone else thought about it before me!
Made some changes to fix/enhance a few parts of the functionality. I've also make some more "stylistic tweaks" that you may or may not appreciate (I can remove them if you'd rather not change them).

- Switch statement rather than if/else if/else when setting SES mail output (slightly more performant).
- Assign variables to object directly in email output rather than defining local variables.
- Applied parseInt() to interval timer to ensure it gets cast correctly (added default of 1m).
- Fix email variable requirements. SES is now disabled by default and secondary vars are only checked if it is set to be enabled.
- Added LOG_TO_STDOUT option (useful for docker/kubernetes).
- Boolean env variables are converted using JSON.parse() to ensure they are indeed the correct type.

### CODE REVIEW

**Comment by tombastianello** [comment]
@sjmayotte Any interest in this?

**Comment by sjmayotte** [comment]
@tombastianello thanks!  I'll plan to merge shortly

**Comment by tombastianello** [comment]
@sjmayotte awesome!

**Comment by alexisuk24** [comment]
Hey y'all any luck with getting this PR merged?

**Comment by sjmayotte** [comment]
Merged just now.  Sorry for the delay, got busy at work.  Should be available in latest tag of container now.  Feel free to add any other changes in another PR and I'll try and merge faster next time 😄

**Pull request merged**
