### PR TITLE
New features and reducing technical debt

### PR DESCRIPTION
**Pull request by ismarslomic**
As a thank you for a simple and useful solution, I want to contribute back to the community and implement new features and reduce technical debt so this repo still stays relevant and secure for all users!

I know that contributing guidelines states to keep the changes as focused as possible, but since I felt need to greater changes I'm submitting one PR with many focused commits. I hope it is not too hard to the review and that this PR will be merged. If you need help I would be happy to be added as contributor so I can continue contributing to this repo.

Following have been changed in this PR:

### New features

1. #23 support running the docker container with alternate user by writing `application.log` and `last-known-ip.txt` to new folder `data` with read/write permissions to all users
2. #27 support specifying a list of domains in config, typically useful for wildcard records
3. #30 bump base image to `node:18.4.0-alpine3.17`, all node dependencies to latest version and remove dependency to `forever-monitor`, which has not been maintained for over 2 years and has security vulnerabilities.
4. support changing the timezone in docker container by use of `TZ` env variable

### Fixes & improvements

- fix Docker build badge
- replace `eslint` with `standard`
- add markdown linting with use of `markdownlint` and fix linting errors in all md files
- add `test` script to `package.json` to run linting in Github actions
- optimize Dockerfile for production mode
- upgrade actions to latest versions in github workflows

### CODE REVIEW

**Comment by sjmayotte** [comment]
@ismarslomic Awesome work!  I just sent you a collaborator invite.  Happy to have the help and I look forward to your contribution!

**Comment by sjmayotte** [comment]
@ismarslomic Snyk secret is already in there.  The action ran successfully after you merged to master.  All good now?

Screenshot 2023-02-14 at 2 38 42 PM

**Comment by ismarslomic** [comment]
I think the issue with `SNYK_TOKEN` being empty and thus Snyk Container workflow failing, is when the workflow runs for PRs or branches other than `master`. 

Here are two examples:

1. My PR: https://github.com/sjmayotte/route53-dynamic-dns/actions/runs/4168756869
2. Dependabot PR: https://github.com/sjmayotte/route53-dynamic-dns/actions/runs/3864378669

I had similar issue with dependabot PRs in my own repo and I resolved it by adding `SNYK_TOKEN` to **Actions** and **Dependabot** sections of **Secrets and variables**.

**Comment by sjmayotte** [comment]
Makes sense.  I just added SNYK_TOKEN to dependabot section.

**Comment by ismarslomic** [comment]
Will test soon when I push new changes to new branch 🙏

**Pull request merged**
